apiVersion: v1
kind: Service
metadata:
  name: predicast-forecast
spec:
  selector:
    app: predicast
    component: forecast
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
